version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Initializing environment"
      - echo "Setting AWS region to eu-central-1"
      - export AWS_DEFAULT_REGION=eu-central-1
      - aws --version
      - echo "Attempting to get CodeArtifact token..."
      - |
        if ! TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 064370794857 --query authorizationToken --output text --region eu-central-1); then
          echo "Failed to get CodeArtifact token. Check IAM permissions and region settings."
          aws sts get-caller-identity
          exit 1
        fi
      - export CODEARTIFACT_AUTH_TOKEN="$TOKEN"
      - echo "CodeArtifact Token retrieved successfully"
  build:
    commands:
      - echo "Build started on $(date)"
      - mvn -s settings.xml -X package
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no